### PR TITLE
Exposing port in dockerfile so it can be used in CI pipeline

### PR DESCRIPTION
**Pull request by maacarbo**
I'm currently facing an issue with gitlab to use this image as a service for my build because it doesn't expose any ports in its Dockerfile.

### CODE REVIEW

**Comment by emelyaart** [comment]
Faced exactly the same problem, I support that.

**Comment by gvenzl** [comment]
Hi @maacarbo,

Thanks a lot for your contribution to these images!

I am very hesitant to reintroduce `EXPOSE` or `VOLUME` (not applicable here, of course) into these images. I did this very early on years ago (with other images) and it made things rather painful for users who wanted to consume these images as base images. The trouble with these two instructions was and still is (see [here](https://stackoverflow.com/questions/57612205/does-exposing-ports-in-a-dockerfile-base-image-expose-them-in-a-final-image), [here](https://github.com/moby/moby/issues/2210), [here](https://github.com/moby/moby/issues/3465) (only open since 8 years old...), [here](https://stackoverflow.com/questions/61595224/undo-dockerfile-volume-directive-from-a-base-image) and [here](https://forums.docker.com/t/why-use-the-volume-instruction/55420)) that they cannot be undone in child images. Granted, the `VOLUME` instruction was much more painful as it forced files not to be part of the container, but still, a user may want to extend the image by, e.g. adding his app to it and not expose the database ports directly anymore. If `EXPOSE` is part of the base images here, there is no way to do this.

With that background, what's much more interesting to me is why you need/want `EXPOSE`? So far I haven't come across any situation where a user cannot expose whatever ports he wants, with or without the `EXPOSE` instruction. For example, GitHub Actions has a directive `ports` that cares very little about an `EXPOSE` instruction:

```
 services:

      # Oracle service (label used to access the service container)
      oracle:

        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-xe:latest

        # Provide passwords and other environment variables to container
        env:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: my_user
          APP_USER_PASSWORD: my_password_which_I_really_should_change

        # Forward Oracle port
        ports:
          - 1521:1521

        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
```

And so do other solutions, like Kubernetes or just simple `podman|docker run -p`.

As I have never used GitLab, please help me to understand why `EXPOSE` is a requirement there?

**Comment by maacarbo** [comment]
Hi @gvenzl,

First of all, sorry for the (way to) late response. 

Thank you for the elaborated explanations.
Once read, I fully agreed with it.

The problem I had was with GitLab. If no ports are exposed a service in an job will not be accessible.
I was able to fix it by adding following yaml tag to the service section of the .gitlab-ci.yaml file
`command: [ "--port", "1521" ]`
```yaml
maven-build:
  extends: .maven-build-base
  services:
    - name: "gvenzl/oracle-xe:11"
       alias: "oracle11"
       command: [ "--port", "1521" ]
       variables:
         ORACLE_RANDOM_PASSWORD: "yes"
         APP_USER: "user"
         APP_USER_PASSWORD: "password"
```
I didn't find it well [documented on the GItLab doc](https://docs.gitlab.com/ee/ci/services/) (thouth it applied like the `CMD` command in the image).

The first solution I did was to extend your image as follow (could have don that from the beginning):
```Dockerfile
FROM gvenzl/oracle-xe:11

EXPOSE 1521/tcp
```

**Comment by gvenzl** [comment]
Hey @maacarbo,

Thanks for coming back and for the additional insights! I'm sure it will help future GitLab users as this is not the first time I have come across this question with GitLab.

And, of course once again, thanks for using these images!

Thanks,

**Comment by kawoki** [comment]
Hi @maacarbo, 

I am also encountering this problem. Tried your `command` solution but it does not work on my side. It shows `FATAL: No HOST or PORT found`. 

Is it because I'm using 18.4.0?

Here's my .yml config
```yml
image: $CI_REGISTRY/user/sqlplus:latest #this is instant client
services:
  - name: "gvenzl/oracle-xe:18.4.0"
    alias: "oracle18"
    command: ["--port", "1521"]
    variables:
      ORACLE_PASSWORD: $ORACLE_PASSWORD
      APP_USER: "test"
      APP_USER_PASSWORD: "password"
```

Thanks in advance.

**Comment by slieschke** [comment]
Setting `command: ["--port", "1521"]` in the service configuration for the job didn't work for me either. The service documentation for the `command` setting at https://docs.gitlab.com/ee/ci/services/#available-settings-for-services states:

> Command or script that should be used as the container’s command. It’s translated to arguments passed to Docker after the image’s name. The syntax is similar to [Dockerfile’s CMD](https://docs.docker.com/reference/dockerfile/#cmd) directive, where each shell token is a separate string in the array.

The `gvenzl/oci-oracle-xe` image entry point script doesn't support any `--port` argument, so AFAIK setting that will have no effect.

Per https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works GitLab will inspect the exposed ports of the image and check they are available when starting a service for a job. As the `gvenzl/oci-oracle-xe` images don't `EXPOSE` any port the job logs will report `*** WARNING: Service XYZ probably didn't start properly`. The service will eventually start successfully although your script won't necessarily wait until the database port is available. If [the Docker executor](https://docs.gitlab.com/runner/executors/docker.html) is being used to run your jobs you can [set a `HEALTHCHECK_TCP_PORT` variable that declares the port that should be used for the service health check](https://docs.gitlab.com/runner/executors/docker.html#how-gitlab-runner-performs-the-services-health-check) so the job waits for your `gvenzl/oci-oracle-xe` service to be ready, e.g.

```(yaml)
job:
  services:
    - name: gvenzl/oracle-xe:18-slim-faststart
      alias: oracle
      variables:
        HEALTHCHECK_TCP_PORT: 1521
```

**Pull request closed without merging**
